import type { Metadata } from "next";
import 'bootstrap/dist/css/bootstrap.min.css'
import "./globals.css";
import Navbar from "@/components/navbar";
import Footer from "@/components/footer";
import BootstrapClient from "./bootstrap.client";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
    <Navbar />
    {children}
    <BootstrapClient />
    <Footer />
    </>
  );
}
