"use client"
import { useSession } from "next-auth/react"
import { useRouter } from 'next/navigation';

// export const metadata = {
//   title: 'Next.js',
//   description: 'Generated by Next.js',
// }

export default function AdminLayout({
  children,
}: {
  children: React.ReactNode
}) {
  // const {data: session, status} = useSession({required: true})
  // const router = useRouter();
  // if(status === "loading") return <div>Loading...</div>
  // if(!session) {
  //   router.push("admin/signin")
  //   return null
  // }
  return <>{children}</>;

}
